name: voicetruth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 13.0.20+150

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0

  #Network
  http: ^0.13.3
  web_socket_channel: ^2.1.0
  sentry_flutter: ^6.2.2

  #Links/Share
  flutter_share:
    git:
      url: https://github.com/zatovagul/flutter_share.git
  uni_links: ^0.5.1


  #Json
  json_annotation: ^4.0.0

  #Firebase
  firebase_core: ^1.10.0
  firebase_auth: ^3.1.4
  firebase_crashlytics: ^2.2.4
  firebase_messaging: ^11.1.0
  firebase_remote_config: ^1.0.4
  uuid: ^3.0.5

  #Provider
  provider: ^6.0.1

  intl: ^0.17.0
  flutter_native_timezone: ^2.0.0

  #Storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.7

  #Audio
  audio_service: ^0.17.1
  just_audio:
    git:
#      url: https://github.com/Eittipat/just_audio.git
      url: https://github.com/ryanheise/just_audio.git
      ref: visualizer
      path: just_audio
  audio_session: ^0.1.6

  #MEDIA
  image_picker: ^0.8.4+1

  #Permission
  permission_handler: ^8.1.6
  package_info: ^2.0.2

  #UI
  flutter_local_notifications: ^8.1.1+2
  flutter_inner_drawer: ^1.0.0+1
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_custom_theme: ^0.2.1
  story_view:
    git:
      url: https://github.com/zatovagul/story_view
  flutter_hooks: ^0.17.0
  flutter_visualizers: ^0.0.2
  #flutter_sinusoidals: ^0.1.4
  siri_wave:
    git:
      url: https://github.com/zatovagul/siri_wave
  wave: ^0.2.0
  drop_cap_text: ^1.1.3
  progresso: ^0.3.0
  another_transformer_page_view: ^1.0.1
  loader_overlay: ^2.0.2+1
  mask_text_input_formatter: ^2.0.0
  fluttertoast: ^8.0.8
  webview_flutter: ^2.0.13
  flutter_html: ^2.1.5
  url_launcher: ^6.0.10
  flutter_spinkit: ^5.1.0
  flutter_keyboard_visibility: ^5.1.1
  lottie: ^1.2.1

#dependency_overrides:
#  just_audio_platform_interface:
#    git:
##      url: https://github.com/Eittipat/just_audio.git
#      url: https://github.com/ryanheise/just_audio.git
#      ref: visualizer
#      path: just_audio_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_serializable: ^4.1.0
  build_runner: ^2.1.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/ios/
    - assets/android/
    - assets/general/
    - assets/html/
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
